/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#cdddff",
        "inverse-on-surface": "#f0f0f9",
        "on-secondary": "#ffffff",
        outline: "#737784",
        "on-surface-variant": "#434652",
        "surface-tint": "#285ab9",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#00419d",
        "on-background": "#1a1b21",
        surface: "#faf8ff",
        "tertiary-container": "#873000",
        "on-primary-container": "#a3bcff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b1c6ff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3037",
        "surface-container-highest": "#e2e2ea",
        "on-surface": "#1a1b21",
        "on-secondary-container": "#51617e",
        "on-primary-fixed": "#001946",
        "on-tertiary-container": "#ffa884",
        "surface-container-low": "#f3f3fc",
        secondary: "#4f5f7b",
        "surface-variant": "#e2e2ea",
        background: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e7f0",
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#b1c6ff",
        primary: "#00317b",
        error: "#ba1a1a",
        "surface-dim": "#d9d9e2",
        "surface-container": "#ededf6",
        "outline-variant": "#c3c6d4",
        tertiary: "#622000",
        "primary-fixed": "#d9e2ff",
        "primary-container": "#0747a6",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        margin: "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["30px", { lineHeight: "38px", letterSpacing: "0", fontWeight: "700" }],
        h1: ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" }],
        h2: ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
        h3: ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        button: ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
